[dray] upload survey notification use case guide
moveworks/developer-docs pull request #104
Opened 2024-03-20 20:33 UTC by luckadoo42

First attempt! Lets see how this goes this time.
Use case guide for new Survey notifications in ServiceNow using Events. Created during SKO

2024-03-28 11:43 UTC, sswiderek-moveworks approved these changes
LGTM!

2024-03-28 11:43 UTC, sswiderek-moveworks commented on authentication-guides/servicenow/README.md
> +ServiceNow's API provides a powerful way to automate tasks in within the ServiceNow environment, as well as query any of the miriad of tables, both offered by ServiceNow OOTB or custom. This guide wi
```suggestion
ServiceNow's API provides a powerful way to automate tasks in the ServiceNow environment, as well as query any of the myriad of tables, both offered by ServiceNow OOTB or custom. This guide will show how to create a ServiceNow service account and authenticate with ServiceNow's APIs.
```

2024-03-28 11:43 UTC, sswiderek-moveworks commented on authentication-guides/servicenow/logo.png
change to service now logo
![servicenow](https://github.com/moveworks/developer-docs/assets/27572166/1d0a3851-825b-4a09-945f-d5ee411182a8)

2024-03-28 11:43 UTC, sswiderek-moveworks commented on authentication-guides/servicenow/logo.png
change to servicenow logo
![servicenow](https://github.com/moveworks/developer-docs/assets/27572166/c8050d0b-2b4a-4b68-b577-57718d6c9a27)

2024-03-28 11:43 UTC, sswiderek-moveworks commented on use-case-guides/survey-completion-alerts-servicenow/README.md
> +You just added Survey completion alerts to your Copilot! Check out our other guides for inspiration on what to build next.
```suggestion
You just added Survey completion alerts to your Moveworks Copilot! Check out our other guides for inspiration on what to build next.
```

2024-04-03 20:36 UTC, ajaymerchia requested changes
You also have `Use Case tutorial Survey completion` and `images` as duplicate directories

2024-04-03 20:36 UTC, ajaymerchia commented on use-case-guides/survey-completion-alerts-servicenow/README.md
> +Since we want to integrate with Azure MFA, we should look into their Graph APIs. For this use case, we will need two API calls:
Asure MFA?

2024-04-03 20:36 UTC, ajaymerchia commented on use-case-guides/survey-completion-alerts-servicenow/README.md
> +To execute this task, an automation in ServiceNow should be established. This automation triggers the Events API when a new 'asmt_assessment_instance' record is created. Subsequently, this action ini
asmt_assessment_instance should be in `backticks`

2025-06-30 07:16 UTC, closed without merging