Add ServiceNow Auth guide
moveworks/developer-docs pull request #107
Opened 2024-03-29 16:47 UTC by indrapaul24

2024-04-01 15:11 UTC, ajaymerchia requested changes

2024-04-01 15:11 UTC, ajaymerchia commented on authentication-guides/servicenow/README.md
> +
Swap for https://docs.servicenow.com/bundle/tokyo-platform-administration/page/administer/roles/reference/r_BaseSystemRoles.html

2024-04-01 15:11 UTC, ajaymerchia commented on authentication-guides/servicenow/Authentication Tutorial ServiceNow v2 bf9283817e704a4385a4c5e8ffe8859e/Screenshot_2024-03-07_at_8.35.19_AM.png
Redact Client ID

2024-05-22 03:54 UTC, sarthaksrinivas approved these changes

2024-05-22 03:54 UTC, sarthaksrinivas commented on authentication-guides/servicenow/Authentication Tutorial ServiceNow v2 bf9283817e704a4385a4c5e8ffe8859e/Screenshot_2024-03-07_at_8.35.19_AM.png
![Screenshot_2024-03-07_at_8 35 19_AM](https://github.com/moveworks/developer-docs/assets/3481162/3e6b31a3-5701-470d-8631-5802e296b237)
Indrashis could you re-upload this image?

2024-05-22 03:54 UTC, sarthaksrinivas commented on authentication-guides/servicenow/Authentication Tutorial ServiceNow v2 bf9283817e704a4385a4c5e8ffe8859e/Screenshot_2024-03-07_at_8.35.19_AM.png
![image](https://github.com/moveworks/developer-docs/assets/3481162/45d6ff76-e708-4b97-abdf-b427bcce15a9)

2024-06-19 06:20 UTC, ajaymerchia approved these changes

2024-06-19 06:20 UTC, merged